### PR TITLE
Add Modal popup with styling

### PR DESCRIPTION
**Pull request by weschoi**

### CODE REVIEW

**Review by azmeer — COMMENTED** [review]
Hi Wes,

  it looks like there are changes in client/index.jsx and ticketSubmission which should not be there. Specifically, this pull request backs out the features for instantiating/displaying the seating chart  and the supporting click handlers for the buttons.

  You'll need to git pull --rebase upstream or git revert the commits which caused the changes which affect those files and push the branch again before we can release/merge this branch.

  Let me know if you need help doing this and we can go over it together.

**Comment by weschoi** [comment]
Hey Azmeer,

With Bootstrap (which was implemented by the original team), we can eliminate the state of **isChartOn** and the toggle functions. Bootstrap comes with its own Modal styling and a button to toggle the Modal that it points to. This way there's less code and less logic to understand.

**Comment by azmeer** [comment]
Great! Looks good.

**Review by azmeer — APPROVED** [review]
LGTM!

**Pull request merged**
